import { BsFillMoonStarsFill } from "react-icons/bs";

import { AiFillGithub, AiFillLinkedin, AiFillInstagram } from "react-icons/ai";

import diego from "../public/diego.jpg";
import react from "../public/react.png";
import node from "../public/node.png";
import js from "../public/js.png";
import typescript from "../public/typescript.png";
import html from "../public/html.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

function App() {
  return (
    <div>
      <head>
        <title>Diego Oliveira Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <main className="bg-white px-10 md:px-40 lg:px-60">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-Roboto ">developedbyDiego</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-1 rounded-md ml-8"
                  href="#"
                >
                  Home
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 ">
            <h2 className="text-5xl text-teal-600 font-medium md:text-6xl">
              Diego Oliveira
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">Web Developer</h3>
            <p className="text-md text-gray-800 md:text-xl max-w-xl mx-auto">
              Desenvolvedor front-end apaixonado por programação.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a href="" target="_blank">
              <AiFillInstagram />
            </a>
            <a href="https://github.com/DiegoEstefano" target="_blank">
              <AiFillGithub />
            </a>
            <a
              href="https://www.linkedin.com/in/diego-oliveira-b78079213"
              target="_blank"
            >
              <AiFillLinkedin />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <img src={diego} layout="fill" objectFit="cover" />
          </div>
        </section>

        {/*************************** MINHAS STACKS ***************************/}
        <section>
          <div className="text-center">
            <h3 className="text-3xl py-1">Minhas Stacks</h3>
            <p className="text-md py-2 leading-8 text-gray-800 ">
              Desde de que eu comecei a minha jornada como desenvolvedor venho
              buscando todos os dias aprender e por em prática várias
              tecnologias.
            </p>
          </div>

          <div className=" m-auto lg:flex lg:max-w-4xl gap-10">
            <div className="text-center shadow-lg p-10 lg:h-80 rounded-xl my-10">
              <img className="m-auto" src={react} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">React</h3>
              <p>
                Utilização de <span className="text-teal-500">React</span> para
                a construção de aplicações front-end e consumo de APIs.{" "}
              </p>
            </div>

            <div className="text-center shadow-lg p-10 lg:h-80 rounded-xl my-10">
              <img className="m-auto" src={js} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">JS</h3>
              <p>
                a Uma das linguagens mais utilizadas atualmente no mercado, para
                criação de API's, sites e aplicações web.
              </p>
            </div>

            <div className=" text-center shadow-lg p-10 lg:h-80 rounded-xl my-10">
              <img className="m-auto" src={html} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">HTML & CSS</h3>
              <p>
                Para a criação do corpo e estilização dos sites, utilizo{" "}
                <span className="text-teal-500">HTML & CSS</span> e alguns
                projetos com{" "}
                <span className="text-teal-500">Tailwind css.</span>
              </p>
            </div>
          </div>
        </section>

        {/*************************** QUERO APRENDER ***************************/}
        <section>
          <div className="text-center">
            <h3 className="text-3xl py-1">Desejo aprender</h3>
            <p className="text-md py-2 leading-8 text-gray-800 ">
              Aqui estão algumas tecnologias que desejo aprender a curto prazo.
            </p>
          </div>

          <div className=" m-auto lg:flex lg:max-w-4xl gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <img className="m-auto" src={node} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">NodeJs</h3>
              <p>
                Desejo aprender <span className="text-teal-500">NodeJs</span>{" "}
                pois além de me tornar um dev mais completo, vai para me ajudar
                na implementação do front-end com o lado do servidor e hoje o{" "}
                <span className="text-teal-500">Node</span> é fortemente
                utilizado em grandes empresas como Linkedin, Uber e Paypal.
              </p>
            </div>

            <div className="text-center shadow-lg p-10  rounded-xl my-10">
              <img className="m-auto" src={react} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">React Native</h3>
              <p>
                Com o React Native, construir uma aplicação mobile é algo muito
                mais simples e rápido, pois o código produzido é semelhante ao{" "}
                <span className="text-teal-500">React Js</span> e todo o código
                produzido é convertido na linguagem nativa do sistema IOS ou
                Android.
              </p>
            </div>

            <div className="text-center shadow-lg p-10  rounded-xl my-10">
              <img
                className="m-auto"
                src={typescript}
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">Typescript</h3>
              <p>
                Pretendo me fortalecer no{" "}
                <span className="text-teal-500">Typescript</span> para facilitar
                o desenvolvimento e tipagem dos dados.
              </p>
            </div>
          </div>
        </section>

        {/*************************** Portfolio ***************************/}
        <section>
          <div className="text-center">
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Aqui estão alguns projetos que desenvolvi ou que ainda estou
              desenvolvendo.
            </p>
          </div>
          <div className="flex flex-col gap-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <a
                target="blank"
                href="https://rastreamento-correios-9rle-ievvid3l4-diegoestefano.vercel.app/"
              >
                <img
                  src={web1}
                  className="rounded-lg  object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <img
                src={web2}
                className="rounded-lg  object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <img
                src={web3}
                className="rounded-lg  object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>

            <div className="basis-1/3 flex-1">
              <img
                src={web4}
                className="rounded-lg  object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>

            <div className="basis-1/3 flex-1">
              <img
                src={web5}
                className="rounded-lg  object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <img
                src={web6}
                className="rounded-lg  object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
        <footer className="flex justify-center mt-5 mb-2">
          <h2>Osasco 2022</h2>
        </footer>
      </main>
    </div>
  );
}

export default App;
